In [28]:
import pandas as pd

In [29]:
df = pd.read_csv("../data/raw/train.csv")
df.head()

  essay_id                                          full_text  score
0  000d118  Many people have car where they live. The thin...      3
1  000fe60  I am a scientist at NASA that is discussing th...      3
2  001ab80  People always wish they had the same technolog...      4
3  001bdc0  We all heard about Venus, the planet without a...      4
4  002ba53  Dear, State Senator\n\nThis is a letter to arg...      3

In [30]:
len(df)

17307

In [31]:
def clean_text(text):
    text = text.replace(u'\xa0', u' ').strip()
    return text

In [32]:
df["full_text"] = df["full_text"].apply(clean_text)

In [33]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("google/gemma-3-270m")


def get_text_length(text):
    encoding = tokenizer(text, truncation=False)
    return len(encoding["input_ids"])

In [34]:
df["length"] = df["full_text"].apply(get_text_length)

In [41]:
print("Essays over 1024 tokens:", (df['length'] > 1024).sum())

Essays over 1024 tokens: 146

In [36]:
df[df['length'] > 1500]

      essay_id  ... length
2155   20cb752  ...   1801
2803   29daf40  ...   1591
5158   4d00492  ...   1565
7369   6e990ee  ...   1506
8609   7fe2d12  ...   1626
11548  a9aeeba  ...   1600
14049  ce7d585  ...   1553
15824  e9831f4  ...   1576

[8 rows x 4 columns]

In [37]:
df_shuffled = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [38]:
dev_df   = df_shuffled.iloc[:2000]
test_df  = df_shuffled.iloc[2000:4000]
train_df = df_shuffled.iloc[4000:]

In [39]:
train_df.to_csv("../data/preprocessed/train.csv", index=False)
dev_df.to_csv("../data/preprocessed/dev.csv", index=False)
test_df.to_csv("../data/preprocessed/test.csv", index=False)